// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_A-WXllpoa4QSn3yP-iHYiKrR4DvDEE0',
    appId: '1:701265587614:web:7d515033cea959c1b4ba8f',
    messagingSenderId: '701265587614',
    projectId: 'cuidartrite-be0d8',
    authDomain: 'cuidartrite-be0d8.firebaseapp.com',
    storageBucket: 'cuidartrite-be0d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjykVbVKi58GZosEb42OhTQZTDakO19wE',
    appId: '1:701265587614:android:c65d3ba79c580b5cb4ba8f',
    messagingSenderId: '701265587614',
    projectId: 'cuidartrite-be0d8',
    storageBucket: 'cuidartrite-be0d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgbZZapQBocugWknlZuf6WN5s1J1SMbX0',
    appId: '1:701265587614:ios:a2abd47ab0044ce8b4ba8f',
    messagingSenderId: '701265587614',
    projectId: 'cuidartrite-be0d8',
    storageBucket: 'cuidartrite-be0d8.firebasestorage.app',
    iosBundleId: 'com.example.appOsteoartrite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgbZZapQBocugWknlZuf6WN5s1J1SMbX0',
    appId: '1:701265587614:ios:a2abd47ab0044ce8b4ba8f',
    messagingSenderId: '701265587614',
    projectId: 'cuidartrite-be0d8',
    storageBucket: 'cuidartrite-be0d8.firebasestorage.app',
    iosBundleId: 'com.example.appOsteoartrite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_A-WXllpoa4QSn3yP-iHYiKrR4DvDEE0',
    appId: '1:701265587614:web:b29e1367abb85ab0b4ba8f',
    messagingSenderId: '701265587614',
    projectId: 'cuidartrite-be0d8',
    authDomain: 'cuidartrite-be0d8.firebaseapp.com',
    storageBucket: 'cuidartrite-be0d8.firebasestorage.app',
  );
}
